task:
  name: Tests
  container:
    image: cirrusci/android-sdk:29
    cpu: 4
    memory: 10G
  tests_script: ./gradlew clean test jacocoTestReport
  integration_tests_script: ./gradlew integrationTest